for i in range(0,51):
   f = open("prod_umbrella"+str(i)+".mdp", "w\n")
   distance=float(i)/10-0.1
   print(distance)
   f.write(";run control\n")
   f.write("integrator			            = sd				\n")
   f.write("tinit				            = 0\n")
   f.write("nsteps				            = 10000000 ;20ns	  \n")
   f.write("dt				                = 0.002\n")
   f.write("comm-mode                       = Linear\n")
   f.write("nstcomm				            = 100\n")
   f.write(";output control\n")
   f.write("nstxout                         = 0   \n")
   f.write("nstxout-compressed              = 5000 ;10 ps\n")
   f.write("nstvout                         = 0   \n")
   f.write("nstfout				            = 0\n")
   f.write("nstenergy                       = 5000 ; 10 ps\n")
   f.write("nstlog                          = 5000 ;10 ps\n")
   f.write(";bonds\n")
   f.write("constraint_algorithm		    = lincs	 \n")
   f.write("constraints			            = h-bonds\n")
   f.write("lincs-iter			            = 1		\n")
   f.write("lincs-order			            = 4	\n")
   f.write("continuation			        = yes\n")
   f.write(";neighbor searching\n")
   f.write("cutoff-scheme                   = Verlet\n")
   f.write("ns_type				            = grid		\n")
   f.write("nstlist				            = 10	   \n")
   f.write("pbc                             = xyz               \n")
   f.write("rlist				            = 1.0				\n")
   f.write(";electrstatics\n")
   f.write("coulombtype                     = PME\n")
   f.write("coulomb-modifier                = Potential-shift-Verlet\n")
   f.write("rcoulomb                        = 1.0                         \n")
   f.write(";van der Waals\n")
   f.write("vdwtype				            = cutoff\n")
   f.write("vdw-modifier			        = Potential-shift-Verlet\n")
   f.write("rvdw				            = 1.0\n")
   f.write("DispCorr                        = EnerPres                    \n")
   f.write(";Ewald\n")
   f.write("fourierspacing                  = 0.12  \n")
   f.write("pme-order                       = 4     \n")
   f.write("ewald-rtol                      = 1e-05\n")
   f.write(";Temperature coupling\n")
   f.write("tc-grps				            = system \n")
   f.write("tau-t				            = 2.0             \n")
   f.write("ref-t				            = 298.15       \n")
   f.write(";Pressure coupling\n")
   f.write("pcoupl				            = Parrinello-Rahman\n")
   f.write("pcoupltype                      = isotropic\n")
   f.write("tau-p                           = 2.0\n")
   f.write("ref-p                           = 1.0\n")
   f.write("compressibility                 = 4.5e-5 \n")
   f.write("refcoord-scaling                = COM\n")
   f.write(";Velocity generation\n")
   f.write("; Generate velocities is on \n")
   f.write("gen-vel     = no \n")
   f.write("gen-temp    = 298.15\n")
   f.write("; Pull code for equilibration - attetnion on groups\n")
   f.write("pull                    = yes\n")
   f.write("pull_ncoords            = 1         ; only one reaction coordinate\n")
   f.write("pull_ngroups            = 2         ; two groups defining one reaction coordinate\n")
   f.write("pull_group1_name        = MOL ; X COM of MOL\n")
   f.write("pull_group2_name        = OCT ; Solute is in OCT-A,  B-SOL COM of SOL\n")
   f.write("pull_coord1_type        = umbrella  ; harmonic potential\n")
   f.write("pull_coord1_geometry    = cylinder  ; simple distance increase\n")
   f.write("pull-coord1-vec         = 0 0 1\n")
   f.write("pull-coord1-groups      = 2 1\n")
   f.write("pull_coord1_dim         = N N Y\n")
   f.write("pull_coord1_start       = no       ; not modify pull-coord1-init\n")
   f.write("pull_coord1_init       = "+str(distance)+"       ; not modify pull-coord1-init\n")
   f.write("pull_coord1_rate        = 0.0000    ; 0.0002 nm per ps = 0.2 nm per ns \n")
   f.write("pull_coord1_k           = 1000      ; kJ mol^-1 nm^-2\n")
   f.write("pull-nstxout            = 10 \n")
   f.write("pull-nstfout            = 10 \n")
f.close()
